package com.dubbo.indetity.po;

import com.dubbo.api.po.BaseBean;

/**
 * user
 *
 * @author bianj
 * @version 1.0.0 2020-09-17
 */
public class User extends BaseBean implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 6111899065812654266L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 主键自增Id */
    private Integer userId;

    /** 用户民 */
    private String userName;

    /** 用户密码 */
    private String password;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取主键自增Id
     *
     * @return 主键自增Id
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * 设置主键自增Id
     *
     * @param userId
     *          主键自增Id
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * 获取用户民
     *
     * @return 用户民
     */
    public String getUserName() {
        return this.userName;
    }

    /**
     * 设置用户民
     *
     * @param userName
     *          用户民
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * 获取用户密码
     *
     * @return 用户密码
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * 设置用户密码
     *
     * @param password
     *          用户密码
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}